steps:
  - label: ":terraform: Initialize"
    command:
      - "cd terraform/"
      - "terraform init"
    artifact_paths:
      - ".terraform/**/*"
      - ".terraform.lock.hcl"

  - wait

  - label: ":clipboard: Plan"
    command:
      - "cd terraform/"
      - "terraform plan -out=plan.tfplan"
    artifact_paths:
      - "plan.tfplan"

  - wait

  - block: "Apply"
    prompt: "Apply these changes?"

  - label: ":rocket: Apply"
    command:
      - "cd terraform/"
      - "terraform apply plan.tfplan"
    artifact_paths:
      - "plan.tfplan"
