steps:
  - label: ":terraform: Initialize"
    command: 
      - "trap 'kill -- $$' INT TERM QUIT"
      - "cd terraform/"
      - "printf 'Initializing Terraform...'"
      - "terraform init -upgrade -reconfigure"
      - "ls -la"  # List files to check the presence of .terraform and .terraform.lock.hcl

  - wait

  - label: ":clipboard: Plan"
    command:
      - "trap 'kill -- $$' INT TERM QUIT"
      - "cd terraform/"
      - "printf 'Checking AWS credentials...'"
      - "env | grep AWS"  # Check AWS credentials
      - "printf 'Listing directory contents...'"
      - "ls -la"  # List files again
      - "printf 'Creating Terraform plan...'"
      - "terraform plan -out=plan.tfplan"

  - wait

  - block: "Apply"
    prompt: "Apply these changes?"

  - label: ":rocket: Apply"
    command:
      - "trap 'kill -- $$' INT TERM QUIT"
      - "cd terraform/"
      - "printf 'Applying Terraform changes...'"
      - "terraform apply plan.tfplan"
