steps:
  - label: ":terraform: Initialize"
    command: 
      - "cd terraform/"
      - "terraform init -reconfigure"

  - wait

  - label: ":clipboard: Plan"
    command:
      - "cd terraform/"
      - "terraform plan -out=plan.tfplan"

  - wait

  - block: "Apply"
    prompt: "Apply these changes?"

  - label: ":rocket: Apply"
    command:
      - "cd terraform/"
      - "terraform apply plan.tfplan"

# If you want caching
cache:
  paths:
    - terraform/.terraform
    - terraform/.terraform.lock.hcl
