steps:
  - label: ":terraform: Initialize"
    command: 
      - "trap 'kill -- $$' INT TERM QUIT"
      - "cd terraform/"
      - "printf 'Running terraform init with reconfigure...'"
      - "terraform init -upgrade -reconfigure"

  - wait

  - label: ":clipboard: Plan"
    command:
      - "cd terraform/"
      - "printf 'Creating Terraform plan...'"
      - "terraform plan -out=plan.tfplan"

  - wait

  - block: "Apply"
    prompt: "Apply these changes?"

  - label: ":rocket: Apply"
    command:
      - "cd terraform/"
      - "printf 'Applying Terraform changes...'"
      - "terraform apply plan.tfplan"

