steps:
  - label: ":terraform: Initialize"
    command: "init_terraform.sh"

  - wait

  - label: ":clipboard: Plan"
    command: "plan_terraform.sh"

  - wait

  - block: "Apply"
    prompt: "Apply these changes?"

  - label: ":rocket: Apply"
    command: "apply_terraform.sh"
