steps:
  - label: ":terraform: Initialize"
    command: "buildkite/scripts/init_terraform.sh"

  - wait

  - label: ":clipboard: Plan"
    command: "buildkite/scripts/plan_terraform.sh"

  - wait

  - block: "Apply"
    prompt: "Apply these changes?"

  - label: ":rocket: Apply"
    command: "buildkite/scripts/apply_terraform.sh"
