steps:
  - label: "Test AWS Credentials with Terraform"
    command:
      - "cd terraform/" # Replace with the correct path to your Terraform files
      - "terraform init"
      - "terraform apply -auto-approve"
