steps:
  - label: ":terraform: Initialize"
    command:
      - "cd terraform/"
      - "terraform init -upgrade"

  - wait # Ensure that terraform init completes before moving on to terraform plan

  - label: ":clipboard: Plan"
    command:
      - "cd terraform/"
      - "terraform plan -out=plan.tfplan"

  - wait # Ensure that terraform plan completes before moving on to the apply step

  - block: "Apply"
    prompt: "Apply these changes?"

  - label: ":rocket: Apply"
    command:
      - "cd terraform/"
      - "terraform apply plan.tfplan"
